name: CI

on:
    # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:
    secrets:
      AWS_ECR_REGISTRY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_REGION: us-west-2
  GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
  ECR_URL: ${{ secrets.AWS_ECR_REGISTRY }}
  WHO: ${{ github.actor }}
  GITHUB_LONG_HASH: ${{ github.event.pull_request.head.sha || github.sha }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: withflint/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Configure AWS Credentials
        uses: withflint/configure-aws-credentials@v1-nix
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: withflint/amazon-ecr-login@v1-nix

      - name: Add SHORT_SHA env property with commit short sha
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_LONG_HASH} | cut -c1-7`" >> $GITHUB_ENV

      - name: Build withflint 
        working-directory: ./
        run: |
          nix build .#withflint-image
          skopeo --insecure-policy copy docker-archive:result docker://${{ secrets.AWS_ECR_REGISTRY }}/withflint.com:${SHORT_SHA}
          echo "- published withflint.com:${SHORT_SHA}"
